### PR TITLE
Added install deps from build.yml and release.yml

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Review by makermelissa — APPROVED** [review]
Looks good

**Comment by makermelissa** [comment]
Do we want the requirements file to be more of a "per repo" thing rather than global?

**Comment by evaherrada** [comment]
@makermelissa I thought it was already a "per repo" thing. Should I remove the lines mentioning requirements.txt?

**Comment by siddacious** [comment]
@makermelissa I was thinking about that and for now I think global works, unless you know of any issues it would cause. If there does turn out to be a need for local requirements setup, in the short term we can add a line to the global installer to call a local installer script, then move that callout to the workflows for transparency once things are worked out.

**Comment by evaherrada** [comment]
@siddacious So I should add a requirements.txt file to this PR?

**Comment by siddacious** [comment]
@dherrada it's currently a mix of both; installing the requirements.txt does install local per-repo requirements, but it also installs some global requirements. No need for a requirements.txt here as this repo isn't a library and doesn't install the same way. Ping me on slack or discord if you don't understand

**Comment by makermelissa** [comment]
My thought on that is some CP repos require Blinka and some purposefully don't. It think it would be better to leave it in a per repo state like it is now. Since we already have the requirements.txt infrastructure in place in all of the repos, it makes sense just to have this be part of the GH Actions script.

**Comment by siddacious** [comment]
@makermelissa I see what you're saying. I think as-is, the PR is good. Local repos can define what is in their local requirements.txt (like Blinka or not) and then the install.sh installs some additional things globally.

If you think it should work differently let us know what issues you see and what specifically you think will fix them.

**Comment by makermelissa** [comment]
Gotcha. So let's add an empty requirements.txt file for now to this repo and it should pass the checks.

**Comment by evaherrada** [comment]
@makermelissa On it

**Comment by siddacious** [comment]
huzzah!

**Pull request merged**
